export const EID_QUOTES = [
  "May the light of the crescent moon guide you toward peace, prosperity, and endless joy.",
  "Wishing you a night full of light, a heart full of joy, and an Eid filled with warmth.",
  "May this beautiful night bring your family closer together in love and gratitude.",
  "May the magic of this Eid stay with you today and always. Sending you love and light.",
  "May your heart be filled with the spirit of Eid and your home with endless laughter.",
  "Wishing you a blessed Eid that marks the beginning of another successful year in your life.",
  "May the divine blessings of Allah bring you hope, faith, and joy on Eid-ul-Fitr and forever.",
  "May your day be filled with laughter, love, and endless plates of delicious home-cooked food.",
  "Wishing you a peaceful day. May your heart be light and your home be full of joy and laughter!",
  "Sending warm hugs. May all your prayers be answered and your day be exceptionally bright today.",
  "Hoping this special day is as wonderful as you are. Stay blessed, happy, and healthy always!",
  "May the light of this day shine in your heart all year long. Wishing you a truly beautiful time.",
  "Here’s to a day of gratitude, great company, and even better memories. Enjoy every moment!",
  "May your home be filled with warmth and your heart with peace. Wishing you a day of happiness.",
  "Wishing you a day of togetherness, love, and the sweetest memories with those you hold dear.",
  "May this day bring you closer to your dreams and fill your heart with immense peace and joy.",
  "Sending you love and light. May your prayers be heard and your life be blessed with abundance.",
  "May the spirit of today bring you hope, harmony, and a year full of wonderful new adventures.",
  "Wishing you a celebration filled with laughter, delicious treats, and endless reasons to smile.",
  "May your path be illuminated by grace and your home be a sanctuary of love and happiness today.",
  "Sending my warmest thoughts. May this special occasion bring endless blessings to your doorstep.",
  "May your heart be as light as a feather and your day be as bright as the morning sun. Enjoy!",
  "Wishing you a beautiful day of reflection, gratitude, and joy with your family and friends.",
  "May the blessings of today stay with you forever and guide you toward a future full of peace.",
  "Hoping your day is seasoned with love and served with a side of pure, unadulterated happiness.",
  "May the kindness you show others return to you tenfold on this incredibly special day.",
  "Wishing you a day of sweet surprises, warm company, and a heart full of deep contentment.",
];
